import { motion } from "framer-motion";
import { Activity, Boxes, CircleGauge, Cpu, HardDrive, MemoryStick, RotateCcw, ServerCog } from "lucide-react";
import type { RepositorySnapshot, SlotView } from "../../lib/types";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Progress } from "../../components/ui/Progress";
import { formatBytes, relativeTime, shortId } from "../../lib/utils";

export function ResourcesView({ repository, onResetSlot }: { repository: RepositorySnapshot; onResetSlot: (slot: SlotView) => void }) {
  const resource = repository.resources;
  const idle = repository.slots.filter((slot) => slot.state === "idle").length;
  return <div className="content-page">
    <section className="page-hero page-hero--compact"><div><div className="eyebrow"><CircleGauge size={13} />RESOURCE ADMISSION</div><h1>Resources & slots</h1><p>Configured capacity and service-reported execution state. Host pressure is never estimated by the UI.</p></div></section>
    <div className="resource-cards">
      <ResourceCard icon={Boxes} label="Repository CI runs" value={`${resource.active_runs} / ${resource.repository_concurrency}`} detail={`${resource.queued_runs} waiting · global ceiling ${resource.max_buildsets}`} progress={resource.active_runs / Math.max(1, resource.repository_concurrency) * 100} />
      <ResourceCard icon={Cpu} label="CPU reservations" value={`${resource.cpu_reserved} / ${resource.cpu_tokens || "auto"}`} detail="Atomic step admission" progress={resource.cpu_tokens ? resource.cpu_reserved / resource.cpu_tokens * 100 : undefined} />
      <ResourceCard icon={MemoryStick} label="Memory reservations" value={resource.memory_bytes ? `${formatBytes(resource.memory_reserved)} / ${formatBytes(resource.memory_bytes)}` : "automatic pool"} detail="Reservations, not live RSS" progress={resource.memory_bytes ? resource.memory_reserved / resource.memory_bytes * 100 : undefined} />
      <ResourceCard icon={HardDrive} label="Volume reserve" value={formatBytes(resource.authoritative_volume_available)} detail={`${formatBytes(resource.recovery_reserve)} protected`} progress={Math.min(100, resource.recovery_reserve / Math.max(1, resource.authoritative_volume_available) * 100)} />
    </div>
    <section className="resource-section"><div className="section-title"><div><span className="section-icon"><HardDrive size={16} /></span><div><h2>Storage admission</h2><p>Stable filesystem identities, co-located roles, and enforced free-space thresholds.</p></div></div></div><div className="scheduler-list">{resource.volumes.map((volume) => <div key={volume.id}><span><HardDrive size={14} /></span><div><strong>{volume.roles.join(" · ")}</strong><small>{formatBytes(volume.available_bytes)} free · warning {formatBytes(volume.warning_threshold)} · critical {formatBytes(volume.critical_threshold)}</small></div><Badge tone={volume.state === "healthy" ? "success" : "warning"} dot>{volume.state}</Badge></div>)}</div></section>
    <section className="resource-section"><div className="section-title"><div><span className="section-icon"><ServerCog size={16} /></span><div><h2>Execution slots</h2><p>Detached worktrees reported by the active service lifetime.</p></div></div><Badge tone={idle ? "success" : "neutral"} dot={idle > 0}>{idle} idle</Badge></div>
      {repository.slots.length ? <div className="slot-grid">{repository.slots.map((slot, index) => <motion.article className="slot-card" key={slot.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .04 }}><div className="slot-card__head"><span className={slot.state === "running" ? "is-running" : "is-idle"}><ServerCog size={16} /></span><div><strong>Slot {String(index + 1).padStart(2, "0")}</strong><small>{slot.state}</small></div><Badge tone={slot.health === "healthy" ? "success" : "warning"} dot>{slot.health}</Badge></div><dl><div><dt>Checkout</dt><dd><code>{shortId(slot.checkout_oid?.bytes, 9) || "—"}</code></dd></div><div><dt>Path</dt><dd title={slot.path}>owned slot</dd></div><div><dt>Logical size</dt><dd>not measured</dd></div><div><dt>Last use</dt><dd>{slot.last_used ? relativeTime(slot.last_used) : "never"}</dd></div></dl><Button variant="ghost" size="sm" onClick={() => onResetSlot(slot)} disabled={slot.state !== "idle"}><RotateCcw size={13} />Reset cold</Button></motion.article>)}</div> : <p className="muted-empty">No execution slots have been provisioned in this app lifetime.</p>}
    </section>
    <div className="resource-columns"><section className="resource-section"><div className="section-title"><div><span className="section-icon"><Activity size={16} /></span><div><h2>Gate queue priority</h2><p>Structural prefix order; resource admission is evaluated separately.</p></div></div></div><div className="scheduler-list">{repository.queue.slice(0, 8).map((entry, index) => <div key={entry.item.id}><span>{index + 1}</span><div><strong>{entry.item.metadata.subject}</strong><small>{index === 0 ? "gate head" : `speculative #${index + 1}`}</small></div><Badge tone="neutral">{index === 0 ? "front" : "queued"}</Badge></div>)}</div></section><section className="resource-section"><div className="section-title"><div><span className="section-icon"><CircleGauge size={16} /></span><div><h2>Named resources</h2><p>Exclusive semaphores held by running steps.</p></div></div></div>{Object.keys(resource.named_semaphores).length ? <div className="scheduler-list">{Object.entries(resource.named_semaphores).map(([name, amount]) => <div key={name}><span>{amount}</span><div><strong>{name}</strong><small>reserved across this repository</small></div><Badge tone="violet">held</Badge></div>)}</div> : <p className="muted-empty">No named semaphore is currently reserved. The authoritative volume has {formatBytes(resource.authoritative_volume_available)} free above a protected {formatBytes(resource.recovery_reserve)} reserve.</p>}</section></div>
  </div>;
}

function ResourceCard({ icon: Icon, label, value, detail, progress }: { icon: typeof Cpu; label: string; value: string; detail: string; progress?: number }) {
  return <article className="resource-card"><span><Icon size={18} /></span><div><small>{label}</small><strong>{value}</strong><p>{detail}</p>{progress == null ? <span className="muted-empty">No live utilization sample</span> : <Progress value={progress} tone={progress > 85 ? "warning" : "info"} label={label} />}</div></article>;
}
