import { useEffect, useRef, useState } from "react";
import { AnimatePresence, MotionConfig, motion } from "framer-motion";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { listen } from "@tauri-apps/api/event";
import { openPath, revealItemInDir } from "@tauri-apps/plugin-opener";
import { applyConfiguration, cancel, approve, check, confirmQuit, createWorktree, getNotificationPreferences, initializeRepository, pruneArtifact, pull, purgeCache, push, reconcile, regenerateConfiguration, reloadEnvironment, removeRepository, removeWorktree, reorderQueue, resetSlot, retryItem, setArtifactPinned, setNotificationPreferences, setPaused, snapshotCache, updateFeature, type NotificationPreferences } from "../lib/api";
import { Sidebar } from "./Sidebar";
import { Topbar } from "./Topbar";
import { useAppState } from "./useAppState";
import { QueueView } from "../features/queue/QueueView";
import { ItemInspector } from "../features/queue/ItemInspector";
import { HistoryView } from "../features/history/HistoryView";
import { ResourcesView } from "../features/resources/ResourcesView";
import { ConfigurationView } from "../features/config/ConfigurationView";
import { DoctorView, StorageView } from "../features/system/SystemViews";
import { CommandPalette } from "./CommandPalette";
import { ApproveDialog, ArtifactPruneDialog, CachePurgeDialog, CancelDialog, PreferencesDialog, QuitDialog, ReconcileDialog, ReorderDialog, RepositoryDialog, RepositoryRemoveDialog, RetryDialog, SlotResetDialog, WorktreeDialog, type WorktreeAction } from "./Dialogs";
import { EmptyState } from "./EmptyState";
import { isTauri } from "../lib/utils";
import { Button } from "../components/ui/Button";
import type { ArtifactRecord, RepositorySnapshot, SlotView } from "../lib/types";

export function App() {
  const state = useAppState(); const client = useQueryClient();
  const [repositoryDialog, setRepositoryDialog] = useState(false); const [repositoryToRemove, setRepositoryToRemove] = useState<string | null>(null); const [preferencesOpen, setPreferencesOpen] = useState(false); const [preferencesReady, setPreferencesReady] = useState(false); const [notificationPreferences, setLocalNotificationPreferences] = useState<NotificationPreferences>({ quiet_mode: false, muted_repositories: [] }); const [approveDialog, setApproveDialog] = useState(false); const [checkDialog, setCheckDialog] = useState(false); const [cancelDialog, setCancelDialog] = useState(false); const [reorderDialog, setReorderDialog] = useState(false); const [retryDialog, setRetryDialog] = useState(false); const [reconcileDialog, setReconcileDialog] = useState(false); const [reconcilePreview, setReconcilePreview] = useState<RepositorySnapshot>(); const [worktreeDialog, setWorktreeDialog] = useState(false); const [cachePurgeDialog, setCachePurgeDialog] = useState(false); const [artifactToPrune, setArtifactToPrune] = useState<ArtifactRecord | null>(null); const [quitDialog, setQuitDialog] = useState(false); const [selectedSlot, setSelectedSlot] = useState<SlotView | null>(null); const [commandOpen, setCommandOpen] = useState(false); const [toast, setToast] = useState<{ message: string; tone: "success" | "error" } | null>(null); const toastTimer = useRef<number | null>(null);
  const refresh = () => client.invalidateQueries({ queryKey: ["snapshot"] });
  const openReconcile = () => { if (state.repository) { setReconcilePreview(state.repository); setReconcileDialog(true); } };
  const initializeMutation = useMutation({ mutationFn: ({ path, command }: { path: string; command?: string }) => initializeRepository(path, command), onSuccess: () => { setRepositoryDialog(false); refresh(); notify("Repository initialized"); }, onError: (error) => notify(String(error), "error") });
  const removeRepositoryMutation = useMutation({ mutationFn: () => removeRepository(repositoryToRemove!), onSuccess: (result) => { setRepositoryToRemove(null); refresh(); notify(result.message); }, onError: (error) => notify(String(error), "error") });
  const preferencesMutation = useMutation({ mutationFn: (preferences: NotificationPreferences) => setNotificationPreferences(preferences.quiet_mode, preferences.muted_repositories), onSuccess: (preferences) => { setLocalNotificationPreferences(preferences); setPreferencesOpen(false); notify("Notification preferences saved"); }, onError: (error) => notify(String(error), "error") });
  const approveMutation = useMutation({ mutationFn: ({ revision, worktreePath }: { revision: string; worktreePath: string }) => approve(state.repository!.state.id, revision, worktreePath), onSuccess: () => { setApproveDialog(false); refresh(); notify("Change approved into the gate"); }, onError: (error) => notify(String(error), "error") });
  const checkMutation = useMutation({ mutationFn: ({ revision, worktreePath }: { revision: string; worktreePath: string }) => check(state.repository!.state.id, revision, worktreePath), onSuccess: () => { setCheckDialog(false); refresh(); notify("Independent check started — it cannot promote this change"); }, onError: (error) => notify(String(error), "error") });
  const cancelMutation = useMutation({ mutationFn: () => cancel(state.repository!.state.id, state.selectedItem!.item.id, state.repository!.state.queue_revision), onSuccess: () => { setCancelDialog(false); state.selectItem(null); refresh(); notify("Change canceled; affected prefixes are rebuilding"); }, onError: (error) => notify(String(error), "error") });
  const reorderMutation = useMutation({ mutationFn: () => reorderQueue(state.repository!.state.id, [state.selectedItem!.item.id], state.repository!.state.queue_revision), onSuccess: () => { setReorderDialog(false); refresh(); notify("Queue reordered; affected prefixes are rebuilding"); }, onError: (error) => notify(String(error), "error") });
  const retryMutation = useMutation({ mutationFn: (cold: boolean) => retryItem(state.repository!.state.id, state.selectedItem!.item.id, cold), onSuccess: () => { setRetryDialog(false); refresh(); notify("A new validation attempt was queued"); }, onError: (error) => notify(String(error), "error") });
  const pullMutation = useMutation({ mutationFn: () => pull(state.repository!.state.id), onSuccess: (result) => { refresh(); notify(result.message); }, onError: (error) => notify(String(error), "error") });
  const pushMutation = useMutation({ mutationFn: () => push(state.repository!.state.id), onSuccess: (result) => { refresh(); notify(result.message); }, onError: (error) => notify(String(error), "error") });
  const reconcileMutation = useMutation({ mutationFn: () => reconcile(reconcilePreview!.state.id, reconcilePreview!.observed_master_oid, reconcilePreview!.state.queue_revision), onSuccess: (result) => { setReconcileDialog(false); refresh(); notify(result.message); }, onError: (error) => notify(String(error), "error") });
  const resetSlotMutation = useMutation({ mutationFn: () => resetSlot(state.repository!.state.id, selectedSlot!.id), onSuccess: () => { setSelectedSlot(null); refresh(); notify("Slot quarantined and recreated cold"); }, onError: (error) => notify(String(error), "error") });
  const cacheSnapshotMutation = useMutation({ mutationFn: () => snapshotCache(state.repository!.state.id), onSuccess: (result) => { refresh(); notify(result.message); }, onError: (error) => notify(String(error), "error") });
  const cachePurgeMutation = useMutation({ mutationFn: (allSlots: boolean) => purgeCache(state.repository!.state.id, allSlots), onSuccess: (result) => { setCachePurgeDialog(false); refresh(); notify(result.message); }, onError: (error) => notify(String(error), "error") });
  const artifactPinMutation = useMutation({ mutationFn: ({ artifact, pinned }: { artifact: ArtifactRecord; pinned: boolean }) => setArtifactPinned(state.repository!.state.id, artifact.artifact_id, pinned), onSuccess: (result) => { refresh(); notify(result.message); }, onError: (error) => notify(String(error), "error") });
  const artifactPruneMutation = useMutation({ mutationFn: () => pruneArtifact(state.repository!.state.id, artifactToPrune!.artifact_id), onSuccess: (result) => { setArtifactToPrune(null); refresh(); notify(result.message); }, onError: (error) => notify(String(error), "error") });
  const pauseMutation = useMutation({ mutationFn: () => setPaused(state.repository!.state.id, state.repository!.state.execution_state !== "paused"), onSuccess: () => { refresh(); notify(state.repository?.state.execution_state === "paused" ? "Gate resumed" : "Gate paused"); }, onError: (error) => notify(String(error), "error") });
  const environmentMutation = useMutation({ mutationFn: reloadEnvironment, onSuccess: () => { refresh(); notify("Shell environment reloaded for future buildsets"); }, onError: (error) => notify(String(error), "error") });
  const configMutation = useMutation({ mutationFn: () => applyConfiguration(state.repository!.state.id), onSuccess: () => { refresh(); notify("Configuration validated and applied"); }, onError: (error) => notify(String(error), "error") });
  const regenerateMutation = useMutation({ mutationFn: () => regenerateConfiguration(state.repository!.state.id), onSuccess: () => { refresh(); notify("Configuration regenerated for review"); }, onError: (error) => notify(String(error), "error") });
  const worktreeMutation = useMutation({ mutationFn: (action: WorktreeAction) => action.kind === "create" ? createWorktree(state.repository!.state.id, action.branch, action.destination) : action.kind === "update" ? updateFeature(state.repository!.state.id, action.path) : removeWorktree(state.repository!.state.id, action.path), onSuccess: (result) => { setWorktreeDialog(false); refresh(); notify(result.message); }, onError: (error) => notify(String(error), "error") });
  const quitMutation = useMutation({ mutationFn: confirmQuit, onError: (error) => notify(String(error), "error") });
  function notify(message: string, tone?: "success" | "error") { const resolvedTone = tone ?? (/\b(error|failed|cannot|unavailable|mismatch|conflict|blocked|refus(?:e|ing)|invalid|missing)\b/i.test(message) ? "error" : "success"); if (toastTimer.current !== null) window.clearTimeout(toastTimer.current); setToast({ message, tone: resolvedTone }); toastTimer.current = window.setTimeout(() => { setToast(null); toastTimer.current = null; }, resolvedTone === "error" ? 7_000 : 4_000); }
  useEffect(() => { function key(event: KeyboardEvent) { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setCommandOpen((open) => !open); } if (event.key === "Escape" && commandOpen) setCommandOpen(false); } window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [commandOpen]);
  useEffect(() => { if (!isTauri()) return; let stop: undefined | (() => void); void listen("tollgate://quit-confirmation-required", () => setQuitDialog(true)).then((unlisten) => { stop = unlisten; }); return () => stop?.(); }, []);
  useEffect(() => () => { if (toastTimer.current !== null) window.clearTimeout(toastTimer.current); }, []);
  useEffect(() => { if (!preferencesOpen) { setPreferencesReady(false); return; } setPreferencesReady(false); void getNotificationPreferences().then((preferences) => { setLocalNotificationPreferences(preferences); setPreferencesReady(true); }).catch((error) => notify(String(error), "error")); }, [preferencesOpen]);

  if (state.isLoading) return <div className="loading-shell" role="status" aria-label="Loading Tollgate"><div className="loading-shell__sidebar" /><div className="loading-shell__main"><span /><span /><span /></div><span className="sr-only">Connecting to the Tollgate service…</span></div>;
  if (state.isError) return <main className="onboarding" role="alert"><div className="onboarding__glow" /><div><div className="eyebrow">SERVICE UNAVAILABLE</div><h1>Tollgate could not load.</h1><p>{String(state.error)}</p><div className="onboarding__actions"><Button variant="primary" onClick={() => state.refetch()}>Retry connection</Button></div></div></main>;

  return <MotionConfig reducedMotion="user"><div className="app-shell">
    <Sidebar snapshot={state.snapshot} selectedRepository={state.repository?.state.id} route={state.route} collapsed={state.sidebarCollapsed} onRepository={state.selectRepository} onRoute={state.setRoute} onToggle={state.toggleSidebar} onAdd={() => setRepositoryDialog(true)} onRemove={setRepositoryToRemove} onPreferences={() => setPreferencesOpen(true)} />
    <div className="workspace">
      <Topbar repository={state.repository} route={state.route} onCommand={() => setCommandOpen(true)} onApprove={() => setApproveDialog(true)} onCheck={() => setCheckDialog(true)} onPull={() => pullMutation.mutate()} onPush={() => pushMutation.mutate()} onReconcile={openReconcile} onWorktrees={() => setWorktreeDialog(true)} onPause={() => pauseMutation.mutate()} onRefresh={() => state.refetch()} refreshing={state.isFetching || pullMutation.isPending || pushMutation.isPending} />
      {!state.repository || !state.snapshot?.repositories.length ? <EmptyState onOpen={() => setRepositoryDialog(true)} /> : <div className="workspace__body">
        <main className="main-content"><AnimatePresence mode="wait" initial={false}><motion.div key={state.route} className="route-page" initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -3 }} transition={{ duration: .16 }}>
          {state.route === "queue" && <QueueView repository={state.repository} selectedItemId={state.selectedItem?.item.id ?? null} onSelect={state.selectItem} onApprove={() => setApproveDialog(true)} />}
          {state.route === "history" && <HistoryView repository={state.repository} onSelect={state.selectItem} />}
          {state.route === "resources" && <ResourcesView repository={state.repository} onResetSlot={setSelectedSlot} />}
          {state.route === "storage" && <StorageView repository={state.repository} onSnapshot={() => cacheSnapshotMutation.mutate()} onPurge={() => setCachePurgeDialog(true)} snapshotting={cacheSnapshotMutation.isPending} />}
          {state.route === "configuration" && <ConfigurationView repository={state.repository} onApply={() => configMutation.mutate()} applying={configMutation.isPending} onRegenerate={() => regenerateMutation.mutate()} regenerating={regenerateMutation.isPending} />}
          {state.route === "doctor" && state.snapshot && <DoctorView repository={state.repository} snapshot={state.snapshot} onReload={() => environmentMutation.mutate()} />}
        </motion.div></AnimatePresence></main>
        <ItemInspector view={state.selectedItem} repository={state.repository} onClose={() => state.selectItem(null)} onCancel={() => setCancelDialog(true)} onPromote={() => setReorderDialog(true)} onRetry={() => setRetryDialog(true)} onOpenWorktree={(path) => { if (isTauri()) void openPath(path); }} onOpenArtifact={(path) => { if (isTauri()) void openPath(path); }} onRevealArtifact={(path) => { if (isTauri()) void revealItemInDir(path); }} onPinArtifact={(artifact, pinned) => artifactPinMutation.mutate({ artifact, pinned })} onPruneArtifact={setArtifactToPrune} artifactMutationPending={artifactPinMutation.isPending || artifactPruneMutation.isPending} />
      </div>}
    </div>
    <CommandPalette open={commandOpen} onOpenChange={setCommandOpen} onRoute={state.setRoute} onApprove={state.repository?.state.execution_state === "active" ? () => setApproveDialog(true) : undefined} onCheck={state.repository?.state.execution_state === "active" ? () => setCheckDialog(true) : undefined} onPull={state.repository ? () => pullMutation.mutate() : undefined} onPush={state.repository ? () => pushMutation.mutate() : undefined} onReconcile={state.repository ? openReconcile : undefined} onWorktrees={state.repository ? () => setWorktreeDialog(true) : undefined} onPause={() => pauseMutation.mutate()} paused={state.repository?.state.execution_state === "paused"} canPause={state.repository?.state.execution_state === "active" || state.repository?.state.execution_state === "paused"} onReload={() => environmentMutation.mutate()} />
    <RepositoryDialog open={repositoryDialog} onOpenChange={setRepositoryDialog} onSubmit={(path, command) => initializeMutation.mutate({ path, command })} loading={initializeMutation.isPending} />
    <RepositoryRemoveDialog open={!!repositoryToRemove} onOpenChange={(open) => { if (!open) setRepositoryToRemove(null); }} repository={state.snapshot?.repositories.find((repository) => repository.state.id === repositoryToRemove)} unavailable={state.snapshot?.unavailable_repositories.find((repository) => repository.id === repositoryToRemove)} onConfirm={() => removeRepositoryMutation.mutate()} loading={removeRepositoryMutation.isPending} />
    <PreferencesDialog open={preferencesOpen} onOpenChange={setPreferencesOpen} snapshot={state.snapshot} preferences={notificationPreferences} ready={preferencesReady} onConfirm={(preferences) => preferencesMutation.mutate(preferences)} loading={preferencesMutation.isPending} />
    <ApproveDialog open={approveDialog} onOpenChange={setApproveDialog} repository={state.repository} onSubmit={(revision, worktreePath) => approveMutation.mutate({ revision, worktreePath })} loading={approveMutation.isPending} canSubmit={state.repository?.state.execution_state === "active"} />
    <ApproveDialog mode="check" open={checkDialog} onOpenChange={setCheckDialog} repository={state.repository} onSubmit={(revision, worktreePath) => checkMutation.mutate({ revision, worktreePath })} loading={checkMutation.isPending} canSubmit={state.repository?.state.execution_state === "active"} />
    <CancelDialog open={cancelDialog} onOpenChange={setCancelDialog} repository={state.repository} view={state.selectedItem} onConfirm={() => cancelMutation.mutate()} loading={cancelMutation.isPending} />
    <ReorderDialog open={reorderDialog} onOpenChange={setReorderDialog} repository={state.repository} view={state.selectedItem} onConfirm={() => reorderMutation.mutate()} loading={reorderMutation.isPending} />
    <RetryDialog open={retryDialog} onOpenChange={setRetryDialog} view={state.selectedItem} onConfirm={(cold) => retryMutation.mutate(cold)} loading={retryMutation.isPending} />
    <ReconcileDialog open={reconcileDialog} onOpenChange={setReconcileDialog} repository={reconcilePreview} onConfirm={() => reconcileMutation.mutate()} loading={reconcileMutation.isPending} />
    <WorktreeDialog open={worktreeDialog} onOpenChange={setWorktreeDialog} repository={state.repository} onSubmit={(action) => worktreeMutation.mutate(action)} loading={worktreeMutation.isPending} />
    <SlotResetDialog open={!!selectedSlot} onOpenChange={(open) => { if (!open) setSelectedSlot(null); }} slot={selectedSlot} onConfirm={() => resetSlotMutation.mutate()} loading={resetSlotMutation.isPending} />
    <CachePurgeDialog open={cachePurgeDialog} onOpenChange={setCachePurgeDialog} repository={state.repository} onConfirm={(allSlots) => cachePurgeMutation.mutate(allSlots)} loading={cachePurgeMutation.isPending} />
    <ArtifactPruneDialog open={!!artifactToPrune} onOpenChange={(open) => { if (!open) setArtifactToPrune(null); }} artifact={artifactToPrune} onConfirm={() => artifactPruneMutation.mutate()} loading={artifactPruneMutation.isPending} />
    <QuitDialog open={quitDialog} onOpenChange={setQuitDialog} activeRuns={state.snapshot?.repositories.reduce((total, repository) => total + repository.resources.active_runs, 0) ?? 0} onConfirm={() => quitMutation.mutate()} loading={quitMutation.isPending} />
    <AnimatePresence>{toast && <motion.div className={`toast toast--${toast.tone}`} role={toast.tone === "error" ? "alert" : "status"} initial={{ opacity: 0, y: 20, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 10 }}><span />{toast.message}</motion.div>}</AnimatePresence>
    {!isTauri() && <div className="demo-ribbon">BROWSER PREVIEW · DEMO STATE</div>}
  </div></MotionConfig>;
}
