import { useEffect, useState, type FormEvent } from "react";
import { open } from "@tauri-apps/plugin-dialog";
import { AlertTriangle, ArrowUp, BellOff, Check, FlaskConical, FolderGit2, FolderMinus, FolderPlus, GitCommitHorizontal, GitPullRequest, Info, Layers3, RotateCcw, ShieldCheck, Snowflake, TerminalSquare, Trash2 } from "lucide-react";
import { oidHex, type ArtifactRecord, type QueueItemView, type RepositorySnapshot, type SlotView, type UnavailableRepository } from "../lib/types";
import { isTauri, shortId } from "../lib/utils";
import { Modal } from "../components/ui/Modal";
import { Button } from "../components/ui/Button";
import { Badge } from "../components/ui/Badge";
import type { NotificationPreferences } from "../lib/api";

export function RepositoryDialog({ open: isOpen, onOpenChange, onSubmit, loading }: { open: boolean; onOpenChange: (open: boolean) => void; onSubmit: (path: string, command: string | undefined) => void; loading: boolean }) {
  const [path, setPath] = useState(""); const [command, setCommand] = useState("");
  useEffect(() => { if (isOpen) { setPath(""); setCommand(""); } }, [isOpen]);
  async function choose() { if (!isTauri()) { setPath("/Users/dev/my-project"); return; } const selection = await open({ directory: true, multiple: false, title: "Choose a Git repository" }); if (selection) setPath(selection); }
  return <Modal open={isOpen} onOpenChange={onOpenChange} title="Open a repository" description="Tollgate registers repositories explicitly and never scans your development folders." footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button><Button variant="primary" disabled={!path} loading={loading} onClick={() => onSubmit(path, command || undefined)}>Open repository</Button></>}><div className="dialog-stack"><label className="field"><span>Git repository</span><div className="path-input"><FolderGit2 size={16} /><input value={path} onChange={(event) => setPath(event.target.value)} placeholder="Choose a repository folder" /><Button size="sm" onClick={choose}>Browse…</Button></div></label><label className="field"><span>Initial CI command <small>optional</small></span><div className="text-input"><TerminalSquare size={16} /><input value={command} onChange={(event) => setCommand(event.target.value)} placeholder="Auto-detect from Cargo.toml, package.json, Makefile…" /></div></label><div className="dialog-callout dialog-callout--neutral"><GitCommitHorizontal size={17} /><div><strong>Your <code>master</code> checkout stays yours</strong><p>Tollgate creates an un-checked-out local <code>release</code> branch for certified integration and leaves your files and current branch unchanged.</p></div></div><div className="dialog-callout"><ShieldCheck size={17} /><div><strong>100% local</strong><p>Queue state, logs, artifacts, mirrors, and execution stay on this Mac. Tollgate never uploads telemetry.</p></div></div></div></Modal>;
}

export function RepositoryRemoveDialog({ repository, unavailable, open: isOpen, onOpenChange, onConfirm, loading }: { repository?: RepositorySnapshot; unavailable?: UnavailableRepository; open: boolean; onOpenChange: (open: boolean) => void; onConfirm: () => void; loading: boolean }) {
  const active = [...(repository?.queue ?? []), ...(repository?.checks ?? [])].filter((entry) => !["promoted", "externally-integrated", "failed", "merge-conflict", "dependency-failed", "canceled", "superseded", "infrastructure-exhausted", "check-passed", "check-failed"].includes(entry.item.state)).length;
  return <Modal open={isOpen} onOpenChange={onOpenChange} title="Remove this repository from Tollgate?" description="Only the explicit app registry entry is removed. Repository-local queue, audit, certificates, logs, artifacts, configuration, refs, and backups stay untouched." footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>Keep repository</Button><Button variant="danger" loading={loading} disabled={(!repository && !unavailable) || active > 0} onClick={onConfirm}><FolderMinus size={14} />Remove from app</Button></>}><div className="dialog-stack"><div className="danger-summary"><FolderMinus size={20} /><div><strong>{repository?.state.name ?? unavailable?.name ?? "No repository selected"}</strong><p>{repository?.state.path ?? unavailable?.path}</p></div></div>{unavailable && <div className="dialog-callout"><AlertTriangle size={16} /><p>This registration could not activate: {unavailable.error}</p></div>}{active > 0 ? <div className="dialog-callout"><AlertTriangle size={16} /><p>{active} active queue or check item{active === 1 ? "" : "s"} must finish or be canceled first. This prevents detaching supervision from live work.</p></div> : <div className="dialog-callout dialog-callout--neutral"><Info size={16} /><p>Reopening the same repository restores its durable state exactly. No Git branch, worktree, or Tollgate-owned evidence is deleted.</p></div>}</div></Modal>;
}

export function ApproveDialog({ mode = "approve", open: isOpen, onOpenChange, repository, onSubmit, loading, canSubmit }: { mode?: "approve" | "check"; open: boolean; onOpenChange: (open: boolean) => void; repository?: RepositorySnapshot; onSubmit: (revision: string, worktreePath: string) => void; loading: boolean; canSubmit: boolean }) {
  const [revision, setRevision] = useState("HEAD");
  const [worktreePath, setWorktreePath] = useState(repository?.state.path ?? "");
  useEffect(() => {
    if (isOpen) { setRevision("HEAD"); setWorktreePath(repository?.state.path ?? ""); }
  }, [isOpen, repository?.state.id, repository?.state.path]);
  async function choose() { if (!isTauri()) return; const selection = await open({ directory: true, multiple: false, title: "Choose the source worktree" }); if (selection) setWorktreePath(selection); }
  function submit(event: FormEvent) { event.preventDefault(); if (canSubmit && worktreePath) onSubmit(revision, worktreePath); }
  const independent = mode === "check";
  return <Modal open={isOpen} onOpenChange={onOpenChange} title={independent ? "Run an independent check" : "Approve a change"} description={independent ? "Validate one immutable source commit without changing the promotion queue." : "Capture one immutable source commit and append it to the dependent gate."} footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button><Button variant="primary" loading={loading} disabled={!worktreePath || !canSubmit} onClick={() => onSubmit(revision, worktreePath)}>{independent ? <FlaskConical size={15} /> : <ShieldCheck size={15} />}{independent ? "Run check" : "Approve & validate"}</Button></>}><form className="dialog-stack" onSubmit={submit}><label className="field"><span>Source worktree</span><div className="path-input"><FolderGit2 size={16} /><input value={worktreePath} onChange={(event) => setWorktreePath(event.target.value)} /><Button type="button" size="sm" onClick={choose}>Browse…</Button></div></label><label className="field"><span>Revision</span><div className="text-input"><GitCommitHorizontal size={16} /><input value={revision} onChange={(event) => setRevision(event.target.value)} autoFocus /><Badge tone="neutral">immutable OID</Badge></div><small>Resolved inside this exact clean worktree. Branch movement after capture is ignored.</small></label>{independent ? <div className="approval-preview"><div><span><FlaskConical size={15} /></span><p><small>QUEUE IMPACT</small><strong>No queue mutation</strong></p><Badge tone="success"><Check size={12} />0 runs restart</Badge></div><div><span><ShieldCheck size={15} /></span><p><small>PROMOTION AUTHORITY</small><strong>None — diagnostic only</strong></p><code>direct source</code></div></div> : <div className="approval-preview"><div><span><Layers3 size={15} /></span><p><small>QUEUE IMPACT</small><strong>Append at position {(repository?.queue.length ?? 0) + 1}</strong></p><Badge tone="success"><Check size={12} />0 earlier runs restart</Badge></div><div><span><ShieldCheck size={15} /></span><p><small>TESTED PREFIX</small><strong>{repository?.queue.length ?? 0} queued patch{repository?.queue.length === 1 ? "" : "es"} + this change</strong></p><code>base {shortId(repository?.state.master_oid.bytes, 7)}</code></div></div>}<div className="dialog-callout dialog-callout--neutral"><Info size={16} /><p>{independent ? "The check runs against the source commit directly. A passing result cannot promote it or certify a gate prefix." : "The worktree must be clean; ignored build output is allowed. Root and merge commits are rejected in v1."}</p></div></form></Modal>;
}

export function CancelDialog({ view, repository, open: isOpen, onOpenChange, onConfirm, loading }: { view: QueueItemView | null; repository?: RepositorySnapshot; open: boolean; onOpenChange: (open: boolean) => void; onConfirm: () => void; loading: boolean }) {
  const independent = view?.item.kind === "independent-check";
  const position = repository?.queue.findIndex((candidate) => candidate.item.id === view?.item.id) ?? -1;
  const descendants = independent ? 0 : Math.max(0, (repository?.queue.length ?? 0) - position - 1);
  return <Modal open={isOpen} onOpenChange={onOpenChange} title={independent ? "Cancel this independent check?" : "Cancel and dequeue this change?"} description={independent ? "Cancellation terminates this run without changing the promotion queue." : "Cancellation terminates its active buildset and structurally rebuilds affected descendants."} footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>{independent ? "Keep running" : "Keep in gate"}</Button><Button variant="danger" loading={loading} onClick={onConfirm}>{independent ? "Cancel check" : "Cancel change"}</Button></>}><div className="dialog-stack"><div className="danger-summary"><AlertTriangle size={20} /><div><strong>{view?.item.metadata.subject}</strong><p>This action is recorded permanently in the audit journal.</p></div></div><div className="impact-list"><div><span>{view?.item.state === "running" ? "1" : "0"}</span><p><strong>active buildset terminated</strong><small>Process group receives TERM, then bounded KILL escalation.</small></p></div><div><span>{descendants}</span><p><strong>{independent ? "queue prefixes affected" : `independent descendant${descendants === 1 ? "" : "s"} rebuilt`}</strong><small>{independent ? "Independent checks carry no promotion or structural authority." : "Each receives a new exact prefix without this patch."}</small></p></div></div></div></Modal>;
}

export function ReorderDialog({ view, repository, open: isOpen, onOpenChange, onConfirm, loading }: { view: QueueItemView | null; repository?: RepositorySnapshot; open: boolean; onOpenChange: (open: boolean) => void; onConfirm: () => void; loading: boolean }) {
  const position = repository?.queue.findIndex((candidate) => candidate.item.id === view?.item.id) ?? -1;
  const dependencies = view?.item.dependencies.length ?? 0;
  const affected = position < 0 ? 0 : position + 1;
  return <Modal open={isOpen} onOpenChange={onOpenChange} title="Move this change toward the gate front?" description="Tollgate will preserve hard dependency order and regenerate every speculative prefix whose inputs change." footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>Keep current order</Button><Button variant="primary" loading={loading} disabled={!view || position <= 0} onClick={onConfirm}><ArrowUp size={15} />Move forward</Button></>}><div className="dialog-stack"><div className="approval-preview"><div><span><ArrowUp size={15} /></span><p><small>NEW PRIORITY</small><strong>Move from position {position + 1} toward the front</strong></p><Badge tone="violet">dependencies preserved</Badge></div><div><span><Layers3 size={15} /></span><p><small>VALIDATION IMPACT</small><strong>{affected} prefix{affected === 1 ? "" : "es"} may restart</strong></p><code>{dependencies} hard dependenc{dependencies === 1 ? "y" : "ies"}</code></div></div><div className="dialog-callout dialog-callout--neutral"><Info size={16} /><p>The command carries queue revision {repository?.state.queue_revision ?? 0}. If the queue changes before confirmation, Tollgate rejects it and asks for a fresh preview.</p></div></div></Modal>;
}

export function ReconcileDialog({ repository, open: isOpen, onOpenChange, onConfirm, loading }: { repository?: RepositorySnapshot; open: boolean; onOpenChange: (open: boolean) => void; onConfirm: () => void; loading: boolean }) {
  const active = repository?.queue.filter((entry) => ["constructing", "queued", "preparing", "running", "ready"].includes(entry.item.state)).length ?? 0;
  const pendingPush = repository?.queue.filter((entry) => entry.item.state === "promoted-local-push-pending").length ?? 0;
  const remoteRecovery = repository?.state.block_reasons.some((reason) => reason.code.includes("remote") || reason.code.includes("push")) ?? false;
  const needsReconcile = !!repository && (oidHex(repository.observed_master_oid) !== oidHex(repository.state.master_oid) || pendingPush > 0 || remoteRecovery);
  const changedBase = !!repository && oidHex(repository.observed_master_oid) !== oidHex(repository.state.master_oid);
  const remoteReasons = repository?.state.block_reasons.filter((reason) => reason.code.includes("remote") || reason.code.includes("push")) ?? [];
  return <Modal open={isOpen} onOpenChange={onOpenChange} title={changedBase ? "Adopt the observed local release?" : "Resolve the recorded remote state?"} description={changedBase ? "Reconciliation records external history as an unvalidated base; it never grants that history a pass certificate." : "Reconciliation clears only the frozen remote promises and block evidence shown below; local release remains unchanged."} footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button><Button variant="danger" loading={loading} disabled={!needsReconcile} onClick={onConfirm}>{changedBase ? "Adopt & rebuild" : "Resolve remote state"}</Button></>}><div className="dialog-stack"><div className="danger-summary"><AlertTriangle size={20} /><div><strong>{changedBase ? "External movement remains outside Tollgate proof" : "Remote recovery evidence will be resolved explicitly"}</strong><p>{changedBase ? "Review the exact local release tip before accepting this boundary." : "Review the frozen remote blocks and pending push promises before clearing them."}</p></div></div><dl className="detail-list"><div><dt>Recorded release</dt><dd><code title={oidHex(repository?.state.master_oid)}>{oidHex(repository?.state.master_oid) || "—"}</code></dd></div><div><dt>Observed release</dt><dd><code title={oidHex(repository?.observed_master_oid)}>{oidHex(repository?.observed_master_oid) || "—"}</code></dd></div><div><dt>Queue revision</dt><dd>{repository?.state.queue_revision ?? "—"}</dd></div></dl>{remoteReasons.length > 0 && <div className="dialog-callout"><AlertTriangle size={16} /><p>{remoteReasons.map((reason) => `${reason.code}: ${reason.message}`).join(" · ")}</p></div>}<div className="impact-list">{changedBase && <div><span>{active}</span><p><strong>active gate prefix{active === 1 ? "" : "es"} invalidated</strong><small>Every remaining source is reconstructed and validated from the adopted base.</small></p></div>}{(changedBase || pendingPush > 0) && <div><span>{pendingPush}</span><p><strong>pending remote promise{pendingPush === 1 ? "" : "s"} abandoned</strong><small>Local promotions remain; remote synchronization is recorded separately.</small></p></div>}</div><div className="dialog-callout dialog-callout--neutral"><Info size={16} /><p>The command is idempotent and records this exact observed release plus queue revision in the audit journal.</p></div></div></Modal>;
}

export function SlotResetDialog({ slot, open: isOpen, onOpenChange, onConfirm, loading }: { slot: SlotView | null; open: boolean; onOpenChange: (open: boolean) => void; onConfirm: () => void; loading: boolean }) {
  return <Modal open={isOpen} onOpenChange={onOpenChange} title="Recreate this slot cold?" description="The existing owned worktree is moved to quarantine before a clean replacement is registered." footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>Keep warm slot</Button><Button variant="danger" loading={loading} disabled={!slot || slot.state !== "idle"} onClick={onConfirm}><RotateCcw size={14} />Reset slot</Button></>}><div className="dialog-stack"><div className="danger-summary"><Snowflake size={20} /><div><strong>{slot?.id ?? "No slot selected"}</strong><p>Ignored incremental output in this slot will not be imported into its replacement.</p></div></div><div className="dialog-callout dialog-callout--neutral"><Info size={16} /><p>Queue and audit history are preserved. A running slot cannot be reset until its process group is fully reaped.</p></div></div></Modal>;
}

export function CachePurgeDialog({ repository, open: isOpen, onOpenChange, onConfirm, loading }: { repository?: RepositorySnapshot; open: boolean; onOpenChange: (open: boolean) => void; onConfirm: (allSlots: boolean) => void; loading: boolean }) {
  const [allSlots, setAllSlots] = useState(false);
  useEffect(() => { if (isOpen) setAllSlots(false); }, [isOpen]);
  const published = repository?.seeds.filter((seed) => seed.state === "published") ?? [];
  const bytes = published.reduce((total, seed) => total + seed.logical_size, 0);
  return <Modal open={isOpen} onOpenChange={onOpenChange} title="Purge reusable cache generations?" description="Published seeds are removed through verified owned quarantine paths; audit metadata remains as a tombstone." footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button><Button variant="danger" loading={loading} onClick={() => onConfirm(allSlots)}><Trash2 size={14} />Purge caches</Button></>}><div className="dialog-stack"><div className="impact-list"><div><span>{published.length}</span><p><strong>published seed{published.length === 1 ? "" : "s"} removed</strong><small>{bytes.toLocaleString()} logical bytes; physical APFS impact may differ.</small></p></div><div><span>{allSlots ? repository?.slots.filter((slot) => slot.state === "idle").length ?? 0 : 0}</span><p><strong>idle slot{allSlots ? "s" : ""} recreated cold</strong><small>Active slots are never touched by this operation.</small></p></div></div><label className="toggle-field"><input type="checkbox" checked={allSlots} onChange={(event) => setAllSlots(event.target.checked)} /><span><strong>Also reset every idle slot</strong><small>Discard slot-local ignored output in addition to shared seeds.</small></span></label></div></Modal>;
}

export function ArtifactPruneDialog({ artifact, open: isOpen, onOpenChange, onConfirm, loading }: { artifact: ArtifactRecord | null; open: boolean; onOpenChange: (open: boolean) => void; onConfirm: () => void; loading: boolean }) {
  return <Modal open={isOpen} onOpenChange={onOpenChange} title="Prune this retained artifact?" description="The immutable file is moved through a verified quarantine before its record becomes a permanent tombstone." footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>Keep artifact</Button><Button variant="danger" loading={loading} disabled={!artifact} onClick={onConfirm}><Trash2 size={14} />Prune artifact</Button></>}><div className="dialog-stack"><div className="danger-summary"><AlertTriangle size={20} /><div><strong>{artifact?.source_path ?? "No artifact selected"}</strong><p>{artifact?.size.toLocaleString() ?? 0} logical bytes · hash {shortId(artifact?.hash, 14)}</p></div></div>{artifact?.retention_state === "pinned" && <div className="dialog-callout"><Info size={16} /><p>This artifact is pinned. Explicit pruning overrides that exemption and remains recorded in the audit journal.</p></div>}<div className="dialog-callout dialog-callout--neutral"><Info size={16} /><p>The build result, certificate, event history, and artifact hash remain. The retained file itself cannot be recovered after quarantine cleanup completes.</p></div></div></Modal>;
}

export type WorktreeAction =
  | { kind: "create"; branch: string; destination?: string }
  | { kind: "update"; path: string }
  | { kind: "remove"; path: string };

export function WorktreeDialog({ repository, open: isOpen, onOpenChange, onSubmit, loading }: { repository?: RepositorySnapshot; open: boolean; onOpenChange: (open: boolean) => void; onSubmit: (action: WorktreeAction) => void; loading: boolean }) {
  const [mode, setMode] = useState<"create" | "update" | "remove">("create");
  const [branch, setBranch] = useState("");
  const [path, setPath] = useState("");
  useEffect(() => { if (isOpen) { setMode("create"); setBranch(""); setPath(""); } }, [isOpen]);
  async function choose() { if (!isTauri()) { setPath("/Users/dev/project-feature"); return; } const selection = await open({ directory: true, multiple: false, title: mode === "create" ? "Choose the parent folder for the new worktree" : "Choose a feature worktree" }); if (selection) setPath(selection); }
  const canSubmit = mode === "create" ? branch.trim().length > 0 : path.trim().length > 0;
  function submit() {
    if (mode === "create") onSubmit({ kind: "create", branch: branch.trim(), destination: path.trim() || undefined });
    else onSubmit({ kind: mode, path: path.trim() });
  }
  const copy = mode === "create" ? { title: "Create a feature worktree", description: "Start a branch from the authoritative release tip without checking release out.", action: "Create worktree", icon: <FolderPlus size={15} /> } : mode === "update" ? { title: "Update a feature worktree", description: "Replay its one clean feature commit onto the current authoritative release.", action: "Update worktree", icon: <GitPullRequest size={15} /> } : { title: "Remove a feature worktree", description: "Remove only a clean, exact, non-queued worktree through Git's ownership checks.", action: "Remove worktree", icon: <FolderMinus size={15} /> };
  return <Modal open={isOpen} onOpenChange={onOpenChange} title={copy.title} description={copy.description} footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button><Button variant={mode === "remove" ? "danger" : "primary"} loading={loading} disabled={!canSubmit} onClick={submit}>{copy.icon}{copy.action}</Button></>}><div className="dialog-stack"><div className="dialog-segments" role="tablist" aria-label="Worktree operation"><button role="tab" aria-selected={mode === "create"} className={mode === "create" ? "is-active" : ""} onClick={() => setMode("create")}>Create</button><button role="tab" aria-selected={mode === "update"} className={mode === "update" ? "is-active" : ""} onClick={() => setMode("update")}>Update</button><button role="tab" aria-selected={mode === "remove"} className={mode === "remove" ? "is-active" : ""} onClick={() => setMode("remove")}>Remove</button></div>{mode === "create" && <label className="field"><span>Branch name</span><div className="text-input"><GitCommitHorizontal size={16} /><input autoFocus value={branch} onChange={(event) => setBranch(event.target.value)} placeholder="feature/my-change" /></div></label>}<label className="field"><span>{mode === "create" ? "Destination folder " : "Feature worktree"}{mode === "create" && <small>optional</small>}</span><div className="path-input"><FolderGit2 size={16} /><input value={path} onChange={(event) => setPath(event.target.value)} placeholder={mode === "create" ? "Let Tollgate choose beside the repository" : "Choose an existing linked worktree"} /><Button type="button" size="sm" onClick={choose}>Browse…</Button></div></label><div className={`dialog-callout ${mode === "remove" ? "" : "dialog-callout--neutral"}`}><Info size={16} /><p>{mode === "create" ? <>The new branch starts at release <code>{shortId(repository?.state.master_oid.bytes, 8)}</code>. The authoritative ref remains isolated.</> : mode === "update" ? "Only the narrow v1 shape is accepted: a clean branch exactly one commit ahead of its previous base." : "Removal is refused when the branch or exact source OID is still represented by an active queue item."}</p></div></div></Modal>;
}

export function RetryDialog({ view, open: isOpen, onOpenChange, onConfirm, loading }: { view: QueueItemView | null; open: boolean; onOpenChange: (open: boolean) => void; onConfirm: (cold: boolean) => void; loading: boolean }) {
  const [cold, setCold] = useState(false);
  useEffect(() => { if (isOpen) setCold(false); }, [isOpen]);
  return <Modal open={isOpen} onOpenChange={onOpenChange} title="Retry this validation?" description="Create a new attempt for the same frozen source and current validation inputs." footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button><Button variant="primary" loading={loading} disabled={!view} onClick={() => onConfirm(cold)}><RotateCcw size={14} />Retry validation</Button></>}><div className="dialog-stack"><div className="approval-preview"><div><span><RotateCcw size={15} /></span><p><small>PREVIOUS RESULT</small><strong>{view?.item.terminal_reason ?? view?.item.state}</strong></p><Badge tone="neutral">attempt {(view?.buildset?.attempt ?? 0) + 1}</Badge></div><div><span>{cold ? <Snowflake size={15} /> : <Layers3 size={15} />}</span><p><small>EXECUTION SLOT</small><strong>{cold ? "Fresh cold slot" : "Warm slot eligible"}</strong></p><code>proof is never reused</code></div></div><label className="toggle-field"><input type="checkbox" checked={cold} onChange={(event) => setCold(event.target.checked)} /><span><strong>Force a cold retry</strong><small>Provision a new slot and skip reusable seeds to diagnose cache-sensitive failures.</small></span></label></div></Modal>;
}

export function PreferencesDialog({ snapshot, preferences, ready, open: isOpen, onOpenChange, onConfirm, loading }: { snapshot?: import("../lib/types").AppSnapshot; preferences: NotificationPreferences; ready: boolean; open: boolean; onOpenChange: (open: boolean) => void; onConfirm: (preferences: NotificationPreferences) => void; loading: boolean }) {
  const [quiet, setQuiet] = useState(preferences.quiet_mode);
  const [muted, setMuted] = useState<string[]>(preferences.muted_repositories);
  useEffect(() => { if (isOpen) { setQuiet(preferences.quiet_mode); setMuted(preferences.muted_repositories); } }, [isOpen, preferences]);
  function toggle(id: string) { setMuted((values) => values.includes(id) ? values.filter((value) => value !== id) : [...values, id]); }
  return <Modal open={isOpen} onOpenChange={onOpenChange} title="Preferences" description="Tune failure-only macOS notifications without weakening queue or validation policy." footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button><Button variant="primary" loading={loading || !ready} disabled={!ready} onClick={() => onConfirm({ quiet_mode: quiet, muted_repositories: muted })}>Save preferences</Button></>}><div className="dialog-stack"><label className="toggle-field"><input type="checkbox" checked={quiet} onChange={(event) => setQuiet(event.target.checked)} /><span><strong>Global quiet mode</strong><small>Suppress failure and reconciliation notifications. Durable events and badges continue normally.</small></span></label><div className="preference-list"><div className="preference-list__heading"><BellOff size={15} /><span><strong>Repository notification mute</strong><small>Failure-only alerts remain enabled for every unchecked repository.</small></span></div>{snapshot?.repositories.map((repository) => <label key={repository.state.id}><input type="checkbox" checked={muted.includes(repository.state.id)} onChange={() => toggle(repository.state.id)} /><span><strong>{repository.state.name}</strong><small>{repository.state.path}</small></span></label>)}</div><div className="dialog-callout dialog-callout--neutral"><Info size={16} /><p>Tollgate never notifies for starts, retries, passing builds, promotions, or ordinary invalidation. Quiet and mute settings affect presentation only.</p></div></div></Modal>;
}

export function QuitDialog({ open: isOpen, onOpenChange, activeRuns, onConfirm, loading }: { open: boolean; onOpenChange: (open: boolean) => void; activeRuns: number; onConfirm: () => void; loading: boolean }) {
  return <Modal open={isOpen} onOpenChange={onOpenChange} title="Quit while validation is running?" description="Tollgate will stop admission, terminate every supervised process group, checkpoint durable state, and rerun interrupted buildsets on next launch." footer={<><Button variant="ghost" onClick={() => onOpenChange(false)}>Keep Tollgate running</Button><Button variant="danger" loading={loading} onClick={onConfirm}>Stop {activeRuns} run{activeRuns === 1 ? "" : "s"} & quit</Button></>}><div className="dialog-stack"><div className="danger-summary"><AlertTriangle size={20} /><div><strong>Active commands will not be reported as failed</strong><p>They become infrastructure interruptions and retain durable logs up to the last complete frame.</p></div></div><div className="dialog-callout dialog-callout--neutral"><Info size={16} /><p>Closing the main window does not quit Tollgate. Use this only when you intend to stop the local gate service.</p></div></div></Modal>;
}
